### ISSUE TITLE
Consider adding a pkgdown site to make docs easier to use

### ISSUE THREAD

**Issue by ThomUK** [francisbarton/boundr#2]
Please assign to me if you'd like to do this...

**Comment by francisbarton** [comment]
Done - it would be great if you could do this Tom! There are lots of potential examples that could be illustrated. And it would be a good way to find some more bugs :-)

**Comment by francisbarton** [comment]
Turns out that if you use the [pkgdown GHA](https://github.com/r-lib/actions/blob/v2-branch/examples/pkgdown.yaml) that [_doesn't_ mean](https://github.com/JamesIves/github-pages-deploy-action/discussions/1190#discussioncomment-4909924) you need to use the "GitHub Actions" setting for Pages - you should still just deploy from the gh-pages branch 🙄🙄🙄
![image](https://github.com/francisbarton/boundr/assets/1819920/4d91a123-195d-4fe8-9aab-a5a8c312cfbc)
